name: Bug Report
description: Report a bug.
title: "bug: "
labels: ["bug"]
body:
    - type: input
      id: summary
      attributes:
          label: Summary
          placeholder: "Briefly describe the bug"
      validations:
          required: true
    - type: textarea
      id: steps
      attributes:
          label: Steps to Reproduce
          placeholder: "List the steps to reproduce the bug"
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: Expected Behavior
          placeholder: "What did you expect to happen?"
    - type: textarea
      id: actual
      attributes:
          label: Actual Behavior
          placeholder: "What actually happened?"
    - type: textarea
      id: additional
      attributes:
          label: Additional Information
          placeholder: "Any other details or screenshots"
