name: Format & Lint

on:
    pull_request:
    workflow_dispatch:

jobs:
    apply:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.PAT }}
                  repository: Mopsgamer/space-soup
            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x
            - uses: actions/setup-go@v5
              with:
                  go-version: "1.23.x"
            - name: Check Deno
              run: |
                  deno install --allow-scripts
                  deno lint --fix
                  deno fmt
            - name: Checking Go
              run: |
                  go fmt ./...
            - name: Push formatting changes (if any)
              run: |
                  git diff --quiet || (
                    git config --global user.name "github-actions"
                    git config --global user.email "github-actions@github.com"
                    git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} &&
                    git commit -a -m "style: code formatting" &&
                    git push)
