name: Code format

on:
    push:
        branches-ignore:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    format-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                  go-version: "1.23.x"
            - uses: denoland/setup-deno@v1
              with:
                  deno-version: v2.x
            - name: Checking Deno
              run: |
                  deno lint
                  deno fmt
                  deno fmt --check
                  deno check .
                  deno task compile:client
            - name: Checking Go
              run: |
                  go vet ./...
                  go fmt ./...
                  go build ./...
            - name: Push formatting changes (if any)
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@github.com"
                  git add .
                  git diff --quiet || (git commit -m "chore: code formatting" && git push)
