name: Code format

on:
    pull_request:
    workflow_dispatch:

jobs:
    format-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: "1.23.x"
            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x
            - name: Checking Deno
              run: |
                  deno install --allow-scripts
                  deno run -A scripts/init.ts
                  deno lint
                  deno fmt --check
                  deno check .
                  deno task compile:client
            - name: Checking Go
              run: |
                  go vet ./...
                  go fmt ./...
                  deno task compile:server
                  deno task compile:server:lite
                  deno task compile:server:prod
                  deno task compile:server:test
